FROM node:18

WORKDIR /app

COPY frontend/ /app/

RUN npm install
RUN npm run build

# Use a web server to serve the static files
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
